Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,15 +1,34 @@
 version: 2.1
 
 executors:
-  docker-executor:
+  test-executor:
     docker:
-      - image: cimg/openjdk:15.0  # CircleCI's OpenJDK image
+      - image: cimg/openjdk:15.0  # Use OpenJDK 15 image based on Ubuntu
 
 jobs:
   build_and_push:
-    executor: docker-executor
+    executor: test-executor
+    environment:
+      DOCKER_IMAGE: ${DOCKER_IMAGE:-"tomcat:8.0"}  # Default to tomcat:8.0 if not set
+      DOCKER_REPO: ${DOCKER_REPO}
+      DOCKER_TAG: ${CIRCLE_BUILD_NUM}  # Tag based on CircleCI build number
+      JFROG_BASE_URL: ${JFROG_BASE_URL}
+      JFROG_USERNAME: ${JFROG_USERNAME}
+      JFROG_API_TOKEN: ${JFROG_API_TOKEN}
+      CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}
+
     steps:
       - checkout
+
+      - run:
+          name: Validate Docker Image and Tag
+          command: |
+            echo "DOCKER_IMAGE: ${DOCKER_IMAGE}"
+            echo "DOCKER_TAG: ${DOCKER_TAG}"
+            if [[ -z "${DOCKER_IMAGE}" || -z "${DOCKER_TAG}" ]]; then
+              echo "Error: DOCKER_IMAGE or DOCKER_TAG is not set."
+              exit 1
+            fi
 
       - run:
           name: Build Docker Image
